### ISSUE TITLE
[Question] Setting this up for Windows

### ISSUE THREAD

**Issue by 400HPMustang** [unknownskl/homebridge-smartglass#1]
I'm running Homebridge on Windows. How would I set up your Python rest server on my Windows installation. I've never used Docker before so I'm not sure what I'm doing here.

Thanks!

**Comment by unknownskl** [comment]
Hi 400hpmustang,

I don't have experience with the software on windows (or setting up python on windows), but I can recommend to ask it in their github repo: https://github.com/OpenXbox/xbox-smartglass-rest-python

They have some instructions for virtualenv on there as well, maybe that will help!
