### ISSUE TITLE
Unsure what inputs do

### ISSUE THREAD

**Issue by Spyromaniac31** [unknownskl/homebridge-smartglass#11]
I just installed this plugin and have been able to power on and off my Xbox successfully. However, I can’t tell what the inputs (app, game, etc.) do.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by apexad** [comment]
likely a duplicate of #3

**Comment by unknownskl** [comment]
Correct. Closing issue.
