### ISSUE TITLE
Failed to connect to xbox : false

### ISSUE THREAD

**Issue by Fookes74** [unknownskl/homebridge-smartglass#12]
Getting repeated 'Failed to connect to Xbox: false' lines in my log. Can't seen anything else related to smartglass plugin. 

Running latest version of plugin. 

Is this normal behaviour?

**Comment by unknownskl** [comment]
It is kind of normal behaviour, however the logging is too verbose. I will release a new update soon that will fix this.

**Comment by unknownskl** [comment]
Hey @Fookes74, can you confirm if the update solved the issue?

**Comment by Fookes74** [comment]
Hey, @unknownskl 

Yes and no. Messages in logs have disappeared but I'm still unable to connect to my Xbox - An error message states:

{ status: 'error_discovery',
  error: 'Console was not found on network. Probably failed' }

This happens every time.

**Comment by unknownskl** [comment]
The error means that the console cannot be discovered. Can you ping the xbox when it is on from the device that is running homebridge?

**Comment by Fookes74** [comment]
Ping isn’t working.

**Comment by Fookes74** [comment]
Left ping running - seems to be very intermittent. 
![Screenshot 2019-12-11 at 14 34 50](https://user-images.githubusercontent.com/37369430/70630406-6f99b980-1c23-11ea-949d-d6625836276b.png)

**Comment by unknownskl** [comment]
It looks like you have some connectivity issues. That could cause issues while connecting to the Xbox. Are you able to improve the connectivity?

**Comment by Fookes74** [comment]
Xbox is connected directly via Ethernet cable. Pi running Homebridge is also via ethernet. Haven't had any issues with either devices on anything else or with any other plugins.

**Comment by unknownskl** [comment]
Im going to close this issue. If the problem still exists, please let me know.
