### ISSUE TITLE
Xbox is seen as both ‘on’ and ‘off’ at the same time.

### ISSUE THREAD

**Issue by Hazza42** [unknownskl/homebridge-smartglass#13]
Despite correctly showing wether it’s on or off in the HomeKit UI, when I ask Siri if my Xbox is on, she says ‘the Xbox is on and the Xbox is off’. The big problem with this is that when I add it to a scene, it’s treated like a toggle. So for example if I want my ‘goodnight’ scene to turn off my Xbox, it will turn it on if it’s already off.

**Comment by PerthSteve** [comment]
Schrödinger’s Xbox!

**Comment by mikicof** [comment]
Same here, trying to contribute doing a check for the status before setting it up, but it would only be a workaround for broken scenes...

**Comment by unknownskl** [comment]
I will test this usecase this weekend and report back. If it is indeed an issue i will try to fix it in 0.13.6

**Comment by unknownskl** [comment]
Related to #24
