### ISSUE TITLE
Continual 'No Response' when trying to turn on or off

### ISSUE THREAD

**Issue by Fookes74** [unknownskl/homebridge-smartglass#15]
On very rare occasions pressing tile for xbox in home app turns xbox on. Almost always it considers the command but invariably returns a 'no response' note with exclamation icon on the Home app tile. 

I have a static IP address set for the xbox on my router and I've configured as below (missing the sensitive info):
{
            "accessory": "Smartglass",
            "name": "Xbox One",
            "liveid": "FD*****************",
            "consoleip": "192.168.1.92",
            "plugin_map": {
                "plugin_name": "homebridge-smartglass",
                "index": 0
            },
            "apps": []
        },

I've simply never been able to get this to work correctly. Nothing obvious showing as an error in the logs either.

**Comment by skitzow88** [comment]
same issue over here

**Comment by unknownskl** [comment]
Related to #24
