### ISSUE TITLE
No volume controls

### ISSUE THREAD

**Issue by mikicof** [unknownskl/homebridge-smartglass#16]
Hi!

I have the xbox configured to set the TV volume via IR and I've seen that in the code there are methods to send it but I can't see the controls on the remote page, when asking siri she says that she can't do that, maybe something is broken?

Thank you

**Comment by muzzymate** [comment]
If you go to the Remote from Control Center pull down menu, can you change the volume by using the side volume buttons of the iPhone? If you have more than one "Homekit TV", you may first need to change to your Xbox remote here.

**Comment by mikicof** [comment]
Oh! Never would I thought of that, works perfectly, thanks!
