### ISSUE TITLE
App uri

### ISSUE THREAD

**Issue by jonathan2000353** [unknownskl/homebridge-smartglass#18]
Where can I find the uri for the apps?

**Comment by Denss02** [comment]
This should help you: https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/find-a-pfn-for-per-app-vpn

**Comment by unknownskl** [comment]
I think you are looking for the App id, in that case you can check the logs for this. It should show it in the logs as following:

> [Smartglass] Xbox switched to app: <app_id>
