### ISSUE TITLE
Unable to power on console from home app 

### ISSUE THREAD

**Issue by b3nnyk22** [unknownskl/homebridge-smartglass#19]
Hello 

I've managed to successfully install the plugin and see my console from the home app. I can power it down. When I try to power it on again I get "No Response" with the exclamation mark on the tile. This is the Homebridge log: 

Failed to connect to xbox: {
  error: 'device_unavailable',
  message: 'Xbox is unavalable on 192.168.0.14'

Any ideas?

Cheers

**Comment by mw2000** [comment]
Same issue here

**Comment by unknownskl** [comment]
Is instant-on configured? If yes, then this looks a bit related to issue #21.

**Comment by alanpooley** [comment]
Same here, instant-on is configured and will allow to turn off but not on

**Comment by unknownskl** [comment]
Can you try the new release of the plugin and see if this has fixed the problem you encounter?
Please check the release notes before upgrading: https://github.com/unknownskl/homebridge-smartglass/releases/tag/1.0.1

**Comment by procannon** [comment]
Hello!

I am still having this issue with the newest update. Here is my log error

status: 'error_discovery',
  error: 'Console was not found on network. Probably failed'

I am setup with a static IP and plugged into the network via ethernet.

**Comment by unknownskl** [comment]
Just to be sure, did you have instant-on configured on the xbox?
I will update the readme with the requirements soon. Seems like this is in the most cases the problem.

**Comment by procannon** [comment]
I do have instant-on configured. I will try to add the Xbox API to see if that helps. 

One thing I didn't add to that comment was that I can turn off the Xbox with the app. The only issue is tuning on from the app.

**Comment by DrPurrple** [comment]
Hello,

Is there an update on that issue? I am experiencing the same thing. And yes, instant on, allow all connections, etc..

**Comment by unknownskl** [comment]
> I do have instant-on configured. I will try to add the Xbox API to see if that helps.
> 
> One thing I didn't add to that comment was that I can turn off the Xbox with the app. The only issue is tuning on from the app.

This is probably an incorrect console id of the xbox. The power on command required the correct console id.
When you use the Xbox API it uses a different way to turn on your console, just like the xbox app does.

> Hello,
> 
> Is there an update on that issue? I am experiencing the same thing. And yes, instant on, allow all connections, etc..

Please try to authenticate with the Xbox API. It fixes a lot of issues.

**Comment by LoneStar1845** [comment]
Hello,

We too are having this issue, even after confirming the api it gave me a different console id then the live console id. Below is what we get:


8/18/2022, 2:50:49 PMSmartglass BridgeSmartglassSmartglass connection timeout detected. Reconnecting...
8/18/2022, 2:50:59 PMSmartglass BridgeSmartglassFailed to turn on xbox using xbox api: {
  status: 404,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "XboxDataNotFound",\r\n' +
    '    "errorMessage": "Xbox not found for user: removedprivateinfo"\r\n' +
    '  },\r\n' +
    '  "result": null,\r\n' +
    '  "uiText": null,\r\n' +
    '  "destination": null,\r\n' +
    '  "userInfo": {}\r\n' +
    '}'
}

Can you help us please
