### ISSUE TITLE
Can't Ping/Can't Connect?  (Feature Request)

### ISSUE THREAD

**Issue by mreassassin** [unknownskl/homebridge-smartglass#21]
I'm having the same problem as many others here...  I can't always ping my xbox when it's in "rest mode".  I think this is a common issue with certain mesh networks (even if you're hardwired).  If I ping my xbox from my Pi that's running homebridge I usually get about 50% or less success.  I'm investigating that from a networking stand point (any help appreciated) to see if I can't get a ping reply closer to 100%.

in the meantime, I'm wondering if this plugin could constantaly send the 'on' command until it reaceives a ping/successful reply.

I've been able to do this with cmdswitch2 with a python script.  if no successful ping is received back to the Pi it will continue call the 'on' command until it is.  I adapted this script to do the continue to call 'on' part and it's been great!

Now I really like this plugin and it's UI within HomeKit!  I love seeing what game/app I'm currently on right there!  can't wait till we can change the apps from HomeKit (but oh the arguments that can start!).

my "hack" was to make a scene in HomeKit that combines my cmdswitch2 xbox-on python script with my smartglass device.  This way when I say 'He siri turn on the xbox' where the smartglass usually fails to turn it on, the python script never fails (well, if it fails it tries and tries again until it succeeds)!

really hoping to get rid of the extra step/hack.

great work on this plugin!!
thanks!!

**Comment by unknownskl** [comment]
I wouldn't recommend to have it keep pinging until it receives an answer but i can definitely implement an option to resend the command for 30 seconds / 1 minute (or even configurable).

**Comment by unknownskl** [comment]
Can you try the new release of the plugin and see if this has fixed the problem you encounter?
Please check the release notes before upgrading: https://github.com/unknownskl/homebridge-smartglass/releases/tag/1.0.1
