### ISSUE TITLE
Siri doesn't recognize success

### ISSUE THREAD

**Issue by kaiserkiwi** [unknownskl/homebridge-smartglass#24]
I have a HomePod mini next to my Xbox (Series X). I just installed your plugin and everything works pretty okay (sometimes it needs a few seconds).

If I say »Hey Siri, turn on my Xbox« it works mostly pretty instantly. But Siri is always saying, that she is waiting for an answer and then tells me, that there was an error. 

Is there any way to get this working right? It's a bit annoying.

**Comment by unknownskl** [comment]
Whoops, didn't meant to close the issue. Can you try the new version 0.16.2?

**Comment by kaiserkiwi** [comment]
I just tried the update.
Siri is completely silent now. Sadly I can't turn off the Xbox now via Siri or the Home App. Turning it in works perfectly though.

**Comment by unknownskl** [comment]
Can you try the new release of the plugin and see if this has been improved?
Please check the release notes before upgrading: https://github.com/unknownskl/homebridge-smartglass/releases/tag/1.0.1
