### ISSUE TITLE
Xbox Appears in Homebridge but not Home

### ISSUE THREAD

**Issue by jrkmtf** [unknownskl/homebridge-smartglass#27]
Hello,

Hoping this is just user error and that I'm missing something.

I updated this plugin to the latest version that uses the new Xbox API, re-did my config file, and aded the API token. My Homebridge logs indicate that it sees my Xbox, that I am authenticated, and I can even control it from within the Homebridge web UI. But, my Xbox does not appear in my Home app. I noticed a line in my log that says to add the Xbox manually using a code, and the code it provides is the same as the Homebridge bridge. Trying to manually add using this code yields no results - Home simply doesn't see my Xbox.

Some additional details, I have an Xbox One S. The Xbox is powered on when I try to manually add it, and I do have instant-on turned on. 

Any thoughts or ideas are much appreciated. Please let me know if I'm a dumb dumb and missed something obvious.

**Comment by unknownskl** [comment]
Hey @jrkmtf,

You should be able to discover the Xbox console as an external accessory.
You can do this by going to the Home app -> Add Accessory -> tap the button 'I don't have a code or cannot scan'. 

The Xbox console should show up over there and then you have to use the same code as homebridge to add it.

Please let me know if this works for you

**Comment by jrkmtf** [comment]
I honestly don't know why this wasn't working when I tried it last night, but I did just now and now I can see it. Chalk it up to me being a dumb dumb.
