### ISSUE TITLE
Where to find AUM_ID & TITLE_ID?

### ISSUE THREAD

**Issue by mralbelo** [unknownskl/homebridge-smartglass#28]
The title is self explanatory but, I'm having issues locating AUM_ID & TITLE_ID.
It would be of great help if you can point me on the right direction, thanks in advance!

**Comment by dprachar2241** [comment]
Same issue

**Comment by dprachar2241** [comment]
[Smartglass] Failed to retrieve titleid from Xbox api (getAppId): 1837352387 Error: getaddrinfo EAI_AGAIN displaycatalog.mp.microsoft.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'displaycatalog.mp.microsoft.com'

**Comment by PewDieMelon** [comment]
> The title is self explanatory but, I'm having issues locating AUM_ID & TITLE_ID.
> It would be of great help if you can point me on the right direction, thanks in advance!

You can hover an app or game from anywhere, press the menu button and select Manage app.</br>
From there you can find File info in the lower left and there is where you can find those ids.</br>
Due to Microsoft killing Smartglass you won't be able to launch anything remotely with current methods afaik.

**Comment by unknownskl** [comment]
You can also get the details from the homebridge log if you are authenticated with the xbox live api. It shows in the following lines in the logs:
`[5/29/2021, 12:10:24 AM] [Smartglass] Xbox app change detected. aum_id: Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application title_id: 750323071
[5/29/2021, 12:10:28 AM] [Smartglass] Xbox app change detected. aum_id: UnknownWorldsEntertainmen.SubnauticaBelowZero_bh1f6rvenfkm2!Game title_id: 1848088335
[5/29/2021, 12:10:31 AM] [Smartglass] Xbox app change detected. aum_id: TwitchInteractive.TwitchApp_7kd9w9e3c5jra!Twitch title_id: 442736763`
