### ISSUE TITLE
Changing inputs fails silently

### ISSUE THREAD

**Issue by ggoodale** [unknownskl/homebridge-smartglass#3]
I have both Netflix and Youtube installed on my XBox, but selecting them via the Inputs selector on my iPhone (iOS 12.2 beta 6) does nothing. Are the IDs hard-coded into the plugin universal? Is there some piece of config I'm missing?

**Comment by unknownskl** [comment]
Since the last xbox update the launch app functionality is broken. There is no solution for it yet.
In version 0.9.4 there is a configuration available to configure the apps. See the example below:

Do not forget to update the plugin first.

`"accessories": [
    {
        "accessory": "Smartglass",
        "name": "Xbox One",
        "address": "127.0.0.1",
        "port": 5557,
        "liveid": "FD00000000000000",
        "consoleip": "192.168.2.5",
        "apps": [
            {
                "name": "Spotify",
                "uri": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App"
            },
            {
                "name": "Youtube",
                "uri": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
            },
            {
                "name": "Netflix",
                "uri": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
            },
            {
                "name": "Airserver",
                "uri": "F3F176BD.53203526D8F6C_p8qzvses5c8me!AirServer",
                "type": "Characteristic.InputSourceType.AIRPLAY"
            }
        ]
    }
],`

**Comment by b3vis** [comment]
any update on this? I see it has a label of wont fix - is this feature to be removed from the plugin?

**Comment by unknownskl** [comment]
As mentioned the xbox launching mechanism is broken which Microsoft has to fix it. For now there is no way to launch apps using the smartglass protocol.

**Comment by unknownskl** [comment]
Small update: It is possible to launch apps using the Microsoft Graph API. Not sure if this should be implemented in the plugin.

**Comment by unknownskl** [comment]
New release supports launchings apps after authenticating with the Xbox Api's.
Please check the release notes and the README: https://github.com/unknownskl/homebridge-smartglass/releases/tag/1.0.1
