### ISSUE TITLE
Turn off not work

### ISSUE THREAD

**Issue by CaseyCZ** [unknownskl/homebridge-smartglass#30]
Can not be turned off. Turn on works.![image](https://user-images.githubusercontent.com/25530709/120111558-aa264780-c172-11eb-9050-cb3f48c52515.jpeg)

**Comment by unknownskl** [comment]
You need to have remote management enabled in the Xbox settings to make use of the api capabilities. Can you double check if that is enabled on the Xbox and if that fixes your problem?

**Comment by CaseyCZ** [comment]
Yes works. Thanks
