### ISSUE TITLE
Failed to retrieve titleid from Xbox api

### ISSUE THREAD

**Issue by nexuscan** [unknownskl/homebridge-smartglass#38]
Hello,

I am getting this error in the log when I am try to open an app in home app.

[DATE, TIME PM] [Smartglass] Failed to retrieve titleid from Xbox api (getAppByTitleId): XXXXXXXX
[DATE, TIME PM] [Smartglass] Rejected app launch (getAppByTitleId) Failed to retrieve titleid from Xbox api:XXXXXXXX

this is my config:

{
            "devices": [
                {
                    "name": "Holy-xbox",
                    "ipaddress": "10.0.5.15",
                    "liveid": "MY_LIVEID_HERE_THAT_I_COPIED_FROM_XBOX_DEVICE",
                    "inputs": [
                        {
                            "name": "Warzone",
                            "aum_id": "iw8Submission-EN-FR_1.0.52.10213_x64__ht1qfjb0gaftw",
                            "title_id": "XXXXXXXX"
                        },
                        {
                            "name": "Forza Horizon 4",
                            "aum_id": "Microsoft.SunriseBaseGame_2.474.687.0_neutral__8wekyb3d8bbwe",
                            "title_id": "XXXXXXXX"
                        }
                    ]
                }
            ],
            "apiToken": "MY_TOKEN_I_COPIED_FROM_URL_OF_CODE_SECTION",
            "platform": "Smartglass"
        }

Can someone help me to solve it ?

many thanks

**Comment by unknownskl** [comment]
I think your token has expired. Can you check the logs after the restart and see if the authentication works?

**Comment by devrimerduman** [comment]
thank you
