### ISSUE TITLE
custom deviceStatus update interval

### ISSUE THREAD

**Issue by cgrin** [unknownskl/homebridge-smartglass#4]
Would it be possible to set a custom interval for polling device status? I'd love to use this in light automations, but as it stands it appears the status is polled every 60 seconds. Ideally I'd like to get this down to 2-3 seconds.

**Comment by unknownskl** [comment]
Release 0.10.0 will have realtime updates. I am rewriting the homebridge plugin to support the native xbox-smartglass-core-node library.

**Comment by unknownskl** [comment]
Implemented in version 0.10.1
