### ISSUE TITLE
Xbox API not working.

### ISSUE THREAD

**Issue by tecdude** [unknownskl/homebridge-smartglass#40]
When I attempt to turn on my xbox from Home it gives this message:

[28/11/2021, 17:15:31] [Smartglass] Failed to turn on xbox using xbox api: {
  status: 404,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "XboxDataNotFound",\r\n' +
    '    "errorMessage": "Xbox not found for user: 0003BFFD275C83FF"\r\n' +
    '  },\r\n' +
    '  "result": null,\r\n' +
    '  "uiText": null,\r\n' +
    '  "destination": null,\r\n' +
    '  "userInfo": {}\r\n' +
    '}'
}

Now I'm getting this error:

Console was not found on network. Probably failed.

Anyone know how to fix. On Xbox Series S

**Comment by unknownskl** [comment]
Im not sure but i think your console id should start with an F. Make sure the console is also configured in the xbox app and connected to your account.
