### ISSUE TITLE
Changing inputs brings up the Home App in the MS Store

### ISSUE THREAD

**Issue by IgorZimmermann** [unknownskl/homebridge-smartglass#44]
I configured Netflix, OneGuide and Spotify as inputs with the proper AUM and title id, but whenever I switch to any of them the Home App comes up in the Microsoft Store.

**Comment by HVR88** [comment]
I get this when switching to "built-in" services like Settings or Dashboard using their IDs (from the log), but installed games seem to launch correctly.

**Comment by IgorZimmermann** [comment]
I figured out the problem! I used the same title id for all the apps, because smartglass showed me that they were the same. After I restarted homebridge the correct title ids were logged.
