### ISSUE TITLE
Can't see remote

### ISSUE THREAD

**Issue by tonyarnold** [unknownskl/homebridge-smartglass#5]
Hi! Thanks for your work on this plugin - it's really great.

I'm having a problem where I cannot see the TV remote for my Xbox on my iPhone. I'm not really sure how to debug - the power switch on and off works, and I seem to be able to change inputs - but no remote functionality. 

What can I provide to help debug this problem?

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/4802/57583016-8b16d780-750f-11e9-82bc-2ab7d5bcfbe7.png">

**Comment by unknownskl** [comment]
Thanks for the bug report! Which homebridge version are you running?

**Comment by tonyarnold** [comment]
Version 0.4.49.

**Comment by unknownskl** [comment]
Thanks, will check my local version and report back. An update of my local homebridge version to 0.4.49 did not make my remote control disappear.

Will debug this and once i know more i will give you an update.

**Comment by unknownskl** [comment]
Hey, just checked and the remote appears fine for me (Testen on an iPhone, i dont have an iPad available to test).
![Uploading IMG_1268.PNG…]()

Are you still having issues?
If yes, how did you name the xbox in your config? The remote should use the same name.
The remote functionality is an integration from homebridge. The plugin gets a call from homebridge to send the control. If the remote doesnt show up, it is probably a bug in Homebridge

**Comment by rowbotik** [comment]
I’m having the same thing as @tonyarnold. I don’t know if I’ve ever had the remote show up but I’m running Homebridge 0.4.49 as well.

**Comment by RealDyllon** [comment]
Running homebridge 0.4.49 as well, same issue. Only my 2017 LG TV appears in the remote on my iPhone running iOS 12.3

**Comment by unknownskl** [comment]
Looks like homebridge got an update to fix this issue: https://github.com/nfarina/homebridge/issues/2208
Will check soon if I can update the homebridge plugin to support this.

**Comment by muzzymate** [comment]
Running into the same issue when sharing the same Homebridge instance. Would love to this worked on when priorities line up. For now, I simply have a second instance of Homebridge running.

**Comment by grzegorz914** [comment]
@unknownskl 

Can U adopt Your code to use new api of homebridge to publisch Xbox as external accessory? This new function solved problem to use more as 1 TV accessory in remote control app on iPhone.
https://github.com/nfarina/homebridge/blob/master/lib/api.js

**Comment by alessiobulfaro** [comment]
Same problem for me. If I remove my LG webOS TV the remote control work fine. But if I turn on the remote control function of my LG webOS TV the Xbox remote control disappear. How suggest @grzegorz914 update the plugin with the latest homebridge API seams to resolve the problem to use as 1 TV accessory.

**Comment by grzegorz914** [comment]
Bump

**Comment by mreassassin** [comment]
is this supposed to do all the controller stuff like the xbox app?  all buttons, directions etc...

**Comment by unknownskl** [comment]
New version is a complete rewrite of the plugin as a platform and supports the new api's.
https://github.com/unknownskl/homebridge-smartglass/releases/tag/1.0.1
