### ISSUE TITLE
Doesn't Show Up in HomeKit App

### ISSUE THREAD

**Issue by bassguy95** [unknownskl/homebridge-smartglass#62]
Does not show up at all in the HomeKit app, not even to turn on/off the xbox.

**Comment by Will123iam** [comment]
Your have to add it manually to the home app. After restarting homebridge in the logs it tells you what to do.

![Screenshot 2023-04-12 at 5 18 56 pm](https://user-images.githubusercontent.com/98259777/231520738-1496a7e9-2240-4475-8db6-91e6d9e58fb0.png)

**Comment by bassguy95** [comment]
> Your have to add it manually to the home app. After restarting homebridge in the logs it tells you what to do.
> 
> ![Screenshot 2023-04-12 at 5 18 56 pm](https://user-images.githubusercontent.com/98259777/231520738-1496a7e9-2240-4475-8db6-91e6d9e58fb0.png)

That... is so simple I'm almost ashamed I missed that. That did it.
